import { ApprovalItem, ApprovalDependencyEdge } from '../src/types/index.js';

export type MasterApprovalDefinition = Omit<
  ApprovalItem,
  'status' | 'daysElapsed' | 'submissionDate' | 'approvedDate' | 'queryDetails'
>;

export const MASTER_APPROVAL_CATALOG: MasterApprovalDefinition[] = [
  {
    id: 'app_sidc_land',
    code: 'SIDC_LAND_ALLOTMENT',
    name: 'Industrial Land Allotment & Possession Sanction',
    title: 'Industrial Land Allotment & Possession Sanction',
    authority: 'State Industrial Development Corporation (SIDC / MIDC / GIDC / SIPCOT)',
    issuingAuthority: 'State Industrial Development Corporation (SIDC / MIDC / GIDC / SIPCOT)',
    category: 'Land, Civil & Zoning',
    portalName: 'State Single Window Investor Portal',
    level: 'State',
    stage: 'pre_establishment',
    slaDays: 30,
    demoProcessingTime: '30 Working Days (Demo SLA)',
    risk: 'low',
    estimatedFeeInr: 150000,
    description:
      'Statutory lease deed, plot possession certificate, and demarcation order within notified government industrial clusters or industrial parks.',
    legalBasis: 'State Industrial Area Development Act & Infrastructure Policy',
    whyApplicable: 'Mandatory prerequisite to establish industrial premises within notified industrial clusters and obtain municipal plotting rights.',
    applicabilityReason: 'Mandatory prerequisite to establish industrial premises within notified industrial clusters and obtain municipal plotting rights.',
    dependencies: [],
    prerequisites: [],
    isCriticalPath: true,
    nextAction: 'Execute registered lease deed and obtain physical site possession certificate from SIDC sub-division office.',
    requiredDocuments: [
      { id: 'doc_sidc_1', code: 'DPR', name: 'Detailed Project Report (DPR)', required: true, format: 'PDF', description: 'Comprehensive technical DPR detailing project cost, installed capacity, and civil layout.' },
      { id: 'doc_sidc_2', code: 'COMPANY_ID', name: 'Certificate of Incorporation / Udyam Registration', required: true, format: 'PDF', description: 'MCA Incorporation Certificate, MOA/AOA, and MSME Udyam credentials.' },
      { id: 'doc_sidc_3', code: 'SITE_LAYOUT', name: 'Site Demarcation & Boundary Coordinate Plan', required: true, format: 'PDF/DWG', description: 'Geographical plot coordinates certified by licensed civil surveyor.' },
    ],
  },
  {
    id: 'app_non_agri_land',
    code: 'NON_AGRI_CONVERSION',
    name: 'Change of Land Use (CLU) / Non-Agricultural (NA) Sanction',
    title: 'Change of Land Use (CLU) / Non-Agricultural (NA) Sanction',
    authority: 'District Collector & Sub-Divisional Magistrate (Revenue Dept)',
    issuingAuthority: 'District Collector & Sub-Divisional Magistrate (Revenue Dept)',
    category: 'Land, Civil & Zoning',
    portalName: 'State Revenue & Land Records Portal',
    level: 'Local',
    stage: 'pre_establishment',
    slaDays: 45,
    demoProcessingTime: '45 Working Days (Demo SLA)',
    risk: 'high',
    estimatedFeeInr: 80000,
    description:
      'Conversion of private agricultural land into certified industrial use under Section 42 of State Land Revenue Code.',
    legalBasis: 'State Land Revenue Code & Town and Country Planning Act',
    whyApplicable: 'Mandatory when establishing manufacturing on private or agricultural land outside notified industrial estates.',
    applicabilityReason: 'Mandatory when establishing manufacturing on private or agricultural land outside notified industrial estates.',
    dependencies: [],
    prerequisites: [],
    isCriticalPath: true,
    nextAction: 'Submit title search report (30-year lineage) and town planning zoning scrutiny application to District Collector.',
    requiredDocuments: [
      { id: 'doc_na_1', code: 'TITLE_SEARCH', name: '30-Year Title Search & Non-Encumbrance Certificate', required: true, format: 'PDF', description: 'Legal search report issued by high court advocate.' },
      { id: 'doc_na_2', code: '7_12_EXTRACT', name: 'Record of Rights (7/12 Extract / Khasra-Khatauni)', required: true, format: 'PDF', description: 'Certified land revenue extract with revenue survey map.' },
    ],
  },
  {
    id: 'app_spcb_cte',
    code: 'SPCB_CTE',
    name: 'Consent to Establish (CTE / NOC)',
    title: 'Consent to Establish (CTE / NOC)',
    authority: 'State Pollution Control Board (SPCB / PCC)',
    issuingAuthority: 'State Pollution Control Board (SPCB / PCC)',
    category: 'Environmental & Pollution',
    portalName: 'OCMMS (Online Consent Management & Monitoring System)',
    level: 'State',
    stage: 'pre_establishment',
    slaDays: 60,
    demoProcessingTime: '45–60 Working Days (Demo SLA)',
    risk: 'high',
    estimatedFeeInr: 85000,
    description:
      'Statutory environmental NOC under Section 25 of Water (Prevention & Control of Pollution) Act 1974 and Section 21 of Air Act 1981 prior to starting physical site construction.',
    legalBasis: 'Water Act 1974, Air Act 1981 & Environment (Protection) Act 1986',
    whyApplicable: 'Mandatory statutory requirement prior to breaking ground for all Red, Orange, and Green category manufacturing facilities.',
    applicabilityReason: 'Mandatory statutory requirement prior to breaking ground for all Red, Orange, and Green category manufacturing facilities.',
    dependencies: ['SIDC_LAND_ALLOTMENT'],
    prerequisites: ['SIDC_LAND_ALLOTMENT'],
    isCriticalPath: true,
    nextAction: 'Upload revised ETP engineering design, water mass balance schematic, and air pollution control equipment specs to SPCB OCMMS portal.',
    requiredDocuments: [
      { id: 'doc_cte_1', code: 'WATER_BALANCE', name: 'Water Balance Diagram & ETP Scheme', required: true, format: 'PDF', description: 'Source-wise water intake, industrial effluent treatment, and zero liquid discharge / recycling plan.' },
      { id: 'doc_cte_2', code: 'PROCESS_FLOW', name: 'Manufacturing Process Flow & Mass Balance', required: true, format: 'PDF', description: 'Raw material inventory, reaction stoichiometry, and point-source air emission inventory.' },
      { id: 'doc_cte_3', code: 'STACK_DETAILS', name: 'Air Pollution Control Equipment (APCE) Layout', required: true, format: 'PDF', description: 'Chimney stack heights, acoustic enclosure specs, and wet scrubbers / bag-filter layouts.' },
    ],
  },
  {
    id: 'app_moef_ec',
    code: 'MOEF_EC',
    name: 'Prior Environmental Clearance (EC)',
    title: 'Prior Environmental Clearance (EC)',
    authority: 'Ministry of Environment, Forest & Climate Change (MoEF&CC) / State SEIAA',
    issuingAuthority: 'Ministry of Environment, Forest & Climate Change (MoEF&CC) / State SEIAA',
    category: 'Environmental & Pollution',
    portalName: 'PARIVESH 2.0 Central Environmental Portal',
    level: 'Central',
    stage: 'pre_establishment',
    slaDays: 105,
    demoProcessingTime: '90–105 Working Days (Demo SLA)',
    risk: 'high',
    estimatedFeeInr: 250000,
    description:
      'Statutory clearance for scheduled high-impact industrial sectors under EIA Notification 2006 (Bulk drugs, Basic chemicals, Metallurgy, Petroleum refining).',
    legalBasis: 'Environment (Protection) Act, 1986 & EIA Notification 2006',
    whyApplicable: 'Required for high-impact CPCB Red category sectors and heavy process chemical/pharmaceutical/metallurgy units.',
    applicabilityReason: 'Required for high-impact CPCB Red category sectors and heavy process chemical/pharmaceutical/metallurgy units.',
    dependencies: ['SIDC_LAND_ALLOTMENT'],
    prerequisites: ['SIDC_LAND_ALLOTMENT'],
    isCriticalPath: true,
    nextAction: 'Commission accredited EIA baseline environmental monitoring report and prepare draft Environmental Management Plan (EMP).',
    requiredDocuments: [
      { id: 'doc_ec_1', code: 'FORM_1', name: 'EIA Form 1 / 1M and Pre-feasibility Report', required: true, format: 'PDF', description: 'Baseline environmental assessment study conducted by NABET-accredited environmental consultant.' },
      { id: 'doc_ec_2', code: 'EIA_EMP', name: 'Draft Environmental Management Plan (EMP)', required: true, format: 'PDF', description: 'Mitigation measures for air emissions, hazardous waste disposal, and local ecological preservation.' },
    ],
  },
  {
    id: 'app_cgwa_noc',
    code: 'CGWA_GROUNDWATER_NOC',
    name: 'CGWA Ground Water Abstraction NOC / Exemption Filing',
    title: 'CGWA Ground Water Abstraction NOC / Exemption Filing',
    authority: 'Central Ground Water Authority (CGWA) / State Ground Water Directorate',
    issuingAuthority: 'Central Ground Water Authority (CGWA) / State Ground Water Directorate',
    category: 'Environmental & Pollution',
    portalName: 'CGWA Online NOC Portal',
    level: 'Central',
    stage: 'pre_establishment',
    slaDays: 45,
    demoProcessingTime: '30–45 Working Days (Demo SLA)',
    risk: 'low',
    estimatedFeeInr: 30000,
    description:
      'Statutory clearance for abstracting groundwater or formal non-abstraction self-declaration when relying 100% on piped industrial municipal supply.',
    legalBasis: 'Environment (Protection) Act, 1986 & CGWA Guidelines 2020',
    whyApplicable: 'Mandatory clearance when withdrawing groundwater via borewells, or mandatory non-abstraction filing when on industrial piped water.',
    applicabilityReason: 'Mandatory clearance when withdrawing groundwater via borewells, or mandatory non-abstraction filing when on industrial piped water.',
    dependencies: ['SIDC_LAND_ALLOTMENT'],
    prerequisites: ['SIDC_LAND_ALLOTMENT'],
    isCriticalPath: false,
    nextAction: 'Submit formal non-abstraction self-declaration along with industrial water supply agreement.',
    requiredDocuments: [
      { id: 'doc_cgwa_1', code: 'HYDRO_REPORT', name: 'Hydrogeological Assessment & Piezometer Scheme', required: false, format: 'PDF', description: 'Aquifer study and water table evaluation by certified hydrogeologist.' },
      { id: 'doc_cgwa_2', code: 'RAINWATER_PLAN', name: 'Rainwater Harvesting (RWH) Artificial Recharge Plan', required: true, format: 'PDF', description: 'Roof-top rainwater harvesting recharge pits design with geo-tagged layout.' },
    ],
  },
  {
    id: 'app_fire_noc_prov',
    code: 'FIRE_NOC_PROVISIONAL',
    name: 'Provisional Fire Safety NOC & Architectural Plan Clearance',
    title: 'Provisional Fire Safety NOC & Architectural Plan Clearance',
    authority: 'State Fire and Emergency Services Directorate / MIDC Fire Brigade',
    issuingAuthority: 'State Fire and Emergency Services Directorate / MIDC Fire Brigade',
    category: 'Safety, Fire & Labour',
    portalName: 'State Fire Clearance Single Window Cell',
    level: 'State',
    stage: 'pre_construction',
    slaDays: 30,
    demoProcessingTime: '30 Working Days (Demo SLA)',
    risk: 'medium',
    estimatedFeeInr: 25000,
    description:
      'Scrutiny of structural building drawings, fire exits, peripheral driveway (6m clearway), static water storage reservoir, and hydrant layout.',
    legalBasis: 'National Building Code (NBC) 2016 Part IV & State Fire Safety Act',
    whyApplicable: 'Mandatory for industrial occupancies having built-up footprint exceeding 500 sq.m or handling flammable inventory.',
    applicabilityReason: 'Mandatory for industrial occupancies having built-up footprint exceeding 500 sq.m or handling flammable inventory.',
    dependencies: ['SIDC_LAND_ALLOTMENT', 'SPCB_CTE'],
    prerequisites: ['SIDC_LAND_ALLOTMENT', 'SPCB_CTE'],
    isCriticalPath: true,
    nextAction: 'Submit fire hydrant network drawings, compartmentation layout, and underground fire water tank (100,000 L) calculations.',
    requiredDocuments: [
      { id: 'doc_fire_1', code: 'FIRE_LAYOUT', name: 'Fire Hydrant & Emergency Escape Layout Plan', required: true, format: 'PDF', description: 'Drafted by licensed fire engineer conforming to NBC 2016 Part IV guidelines.' },
      { id: 'doc_fire_2', code: 'RISK_ANALYSIS', name: 'Fire Load & Industrial Hazard Assessment Report', required: true, format: 'PDF', description: 'Material Safety Data Sheets (MSDS), solvent storage classification, and fire suppression ratings.' },
    ],
  },
  {
    id: 'app_factory_plan',
    code: 'FACTORY_PLAN_APPROVAL',
    name: 'Factory Building Plan Sanction & Machinery Layout Approval',
    title: 'Factory Building Plan Sanction & Machinery Layout Approval',
    authority: 'Directorate of Industrial Safety and Health (DISH) / Chief Inspector of Factories',
    issuingAuthority: 'Directorate of Industrial Safety and Health (DISH) / Chief Inspector of Factories',
    category: 'Safety, Fire & Labour',
    portalName: 'State Labour & Factories Single Window Portal',
    level: 'State',
    stage: 'pre_construction',
    slaDays: 30,
    demoProcessingTime: '30 Working Days (Demo SLA)',
    risk: 'medium',
    estimatedFeeInr: 15000,
    description:
      'Scrutiny and statutory approval of factory shed ventilation, gangways (minimum 1.2m clear), machine guards, worker ergonomics, and sanitary conveniences.',
    legalBasis: 'The Factories Act, 1948 - Section 6',
    whyApplicable: 'Mandatory under Section 6 of The Factories Act 1948 for any manufacturing unit employing 10+ workers with power.',
    applicabilityReason: 'Mandatory under Section 6 of The Factories Act 1948 for any manufacturing unit employing 10+ workers with power.',
    dependencies: ['SIDC_LAND_ALLOTMENT', 'SPCB_CTE', 'FIRE_NOC_PROVISIONAL'],
    prerequisites: ['SIDC_LAND_ALLOTMENT', 'SPCB_CTE', 'FIRE_NOC_PROVISIONAL'],
    isCriticalPath: true,
    nextAction: 'Upload Form 1 application with architectural drawings showing machine safety clearance, natural lighting, and ventilation ratios.',
    requiredDocuments: [
      { id: 'doc_fact_1', code: 'PLANT_LAYOUT', name: 'Machinery Placement & Gangway Layout Plan', required: true, format: 'PDF', description: '1:100 scale drawings displaying worker aisles, machine safety interlocks, and emergency push-buttons.' },
      { id: 'doc_fact_2', code: 'VENT_CALC', name: 'Ventilation & Lighting Luminance Calculation Sheet', required: true, format: 'PDF', description: 'Calculations proving statutory air changes per hour and lux levels per Factory Rules.' },
    ],
  },
  {
    id: 'app_discom_power',
    code: 'DISCOM_POWER_SANCTION',
    name: 'High Tension (HT) Power Sanction & Grid Tapping Sanction',
    title: 'High Tension (HT) Power Sanction & Grid Tapping Sanction',
    authority: 'State Electricity Distribution Company (DISCOM / MSEDCL / TANGEDCO / UGVCL)',
    issuingAuthority: 'State Electricity Distribution Company (DISCOM / MSEDCL / TANGEDCO / UGVCL)',
    category: 'Power, Energy & Utilities',
    portalName: 'DISCOM High-Tension Consumer Portal',
    level: 'State',
    stage: 'pre_construction',
    slaDays: 45,
    demoProcessingTime: '45 Working Days (Demo SLA)',
    risk: 'low',
    estimatedFeeInr: 120000,
    description:
      'Sanction for dedicated HT feeder line tapping, transformer substation approval, and power allocation agreement.',
    legalBasis: 'The Electricity Act, 2003 & State Supply Code',
    whyApplicable: 'Mandatory for industrial connected loads exceeding 50 kVA / 100 HP requiring dedicated 11 kV or 33 kV connection.',
    applicabilityReason: 'Mandatory for industrial connected loads exceeding 50 kVA / 100 HP requiring dedicated 11 kV or 33 kV connection.',
    dependencies: ['SIDC_LAND_ALLOTMENT'],
    prerequisites: ['SIDC_LAND_ALLOTMENT'],
    isCriticalPath: false,
    nextAction: 'Pay demand note charges for 11 kV metering cubicle and sign consumer bulk power agreement.',
    requiredDocuments: [
      { id: 'doc_pwr_1', code: 'LOAD_CHART', name: 'Connected Load List & Single Line Diagram (SLD)', required: true, format: 'PDF', description: 'Certified by licensed A-grade electrical contractor with motor rating schedules.' },
      { id: 'doc_pwr_2', code: 'SUBSTATION_DWG', name: 'Transformer Substation & Earthing Layout Plan', required: true, format: 'PDF', description: 'Earthing pit calculations, neutral earthing scheme, and lightning arrester coordinates.' },
    ],
  },
  {
    id: 'app_ceig_approval',
    code: 'CEIG_ELECTRICAL_APPROVAL',
    name: 'CEIG Electrical Drawing Approval & Substation Energisation NOC',
    title: 'CEIG Electrical Drawing Approval & Substation Energisation NOC',
    authority: 'Chief Electrical Inspector to Government (CEIG), Energy Dept',
    issuingAuthority: 'Chief Electrical Inspector to Government (CEIG), Energy Dept',
    category: 'Power, Energy & Utilities',
    portalName: 'Electrical Inspectorate Single Window Portal',
    level: 'State',
    stage: 'pre_construction',
    slaDays: 21,
    demoProcessingTime: '21 Working Days (Demo SLA)',
    risk: 'medium',
    estimatedFeeInr: 18000,
    description:
      'Statutory inspection and clearance under Central Electricity Authority Regulations for high voltage transformers (>100 kVA), HT switchgear, and safety clearances.',
    legalBasis: 'Central Electricity Authority (Safety & Electric Supply) Regulations 2010',
    whyApplicable: 'Mandatory statutory safety clearance prior to energising high tension transformers or electrical installations above 650 Volts.',
    applicabilityReason: 'Mandatory statutory safety clearance prior to energising high tension transformers or electrical installations above 650 Volts.',
    dependencies: ['DISCOM_POWER_SANCTION'],
    prerequisites: ['DISCOM_POWER_SANCTION'],
    isCriticalPath: false,
    nextAction: 'Schedule electrical pre-commissioning inspection and submit transformer test certificates and earth-pit resistance test logs.',
    requiredDocuments: [
      { id: 'doc_ceig_1', code: 'TRANSFORMER_TEST', name: 'Transformer Routine Test & Oil Breakdown Voltage (BDV) Report', required: true, format: 'PDF', description: 'Manufacturer test certificates certified per IS 2026 / IS 335.' },
      { id: 'doc_ceig_2', code: 'EARTH_RESISTANCE', name: 'Earth Electrode Resistance & Continuity Test Log', required: true, format: 'PDF', description: 'Certified by licensed electrical contractor proving combined earth resistance < 1.0 Ohm.' },
    ],
  },
  {
    id: 'app_water_sanction',
    code: 'WATER_SUPPLY_SANCTION',
    name: 'Industrial Piped Water Connection Sanction',
    title: 'Industrial Piped Water Connection Sanction',
    authority: 'State Industrial Development Corporation (Water Works) / Municipal Corporation',
    issuingAuthority: 'State Industrial Development Corporation (Water Works) / Municipal Corporation',
    category: 'Power, Energy & Utilities',
    portalName: 'Industrial Water Works Consumer Cell',
    level: 'Local',
    stage: 'pre_construction',
    slaDays: 15,
    demoProcessingTime: '15 Working Days (Demo SLA)',
    risk: 'low',
    estimatedFeeInr: 25000,
    description:
      'Sanction and pipe tapping order for dedicated bulk industrial fresh water supply for manufacturing operations, boiler feed, and cooling towers.',
    legalBasis: 'State Industrial Water Supply Regulations & Municipal Act',
    whyApplicable: 'Required to secure physical pipeline tapping and sanctioned daily fresh water quota from industrial estate authorities.',
    applicabilityReason: 'Required to secure physical pipeline tapping and sanctioned daily fresh water quota from industrial estate authorities.',
    dependencies: ['SIDC_LAND_ALLOTMENT'],
    prerequisites: ['SIDC_LAND_ALLOTMENT'],
    isCriticalPath: false,
    nextAction: 'Execute industrial water supply agreement and install calibrated electromagnetic water meter at plant gate boundary.',
    requiredDocuments: [
      { id: 'doc_wtr_1', code: 'WATER_CALC', name: 'Daily Water Consumption & Pipeline Sizing Scheme', required: true, format: 'PDF', description: 'Engineering sheet breaking down process wash, cooling tower makeup, and domestic canteen demand.' },
      { id: 'doc_wtr_2', code: 'PLUMBING_PLAN', name: 'Internal Water Distribution & Flow Metering Scheme', required: true, format: 'PDF', description: 'Isometric diagram showing backflow prevention and storage reservoir capacity.' },
    ],
  },
  {
    id: 'app_boiler_reg',
    code: 'BOILER_REGISTRATION',
    name: 'Steam Boiler Drawing Approval & Hydraulic Test Certificate',
    title: 'Steam Boiler Drawing Approval & Hydraulic Test Certificate',
    authority: 'Chief Inspector of Boilers / Directorate of Steam Boilers',
    issuingAuthority: 'Chief Inspector of Boilers / Directorate of Steam Boilers',
    category: 'Power, Energy & Utilities',
    portalName: 'National Boiler Portal / State Directorate',
    level: 'State',
    stage: 'pre_operation',
    slaDays: 25,
    demoProcessingTime: '25 Working Days (Demo SLA)',
    risk: 'medium',
    estimatedFeeInr: 20000,
    description:
      'Statutory inspection and cold hydrostatic pressure testing prior to firing industrial steam boilers (>22.75 L) or steam distribution pipelines.',
    legalBasis: 'The Indian Boilers Act, 1923 & Indian Boiler Regulations (IBR)',
    whyApplicable: 'Mandatory whenever steam boilers or high-pressure steam vessels are installed for thermal heating, pasteurization, or process drying.',
    applicabilityReason: 'Mandatory whenever steam boilers or high-pressure steam vessels are installed for thermal heating, pasteurization, or process drying.',
    dependencies: ['SPCB_CTE', 'FACTORY_PLAN_APPROVAL'],
    prerequisites: ['SPCB_CTE', 'FACTORY_PLAN_APPROVAL'],
    isCriticalPath: false,
    nextAction: 'Coordinate with Boiler Inspector for on-site cold hydraulic pressure test at 1.5x design working pressure.',
    requiredDocuments: [
      { id: 'doc_blr_1', code: 'IBR_CERT', name: 'IBR Form II, III, & IV Manufacturer Certificates', required: true, format: 'PDF', description: 'Original manufacturer material test records, welders qualification, and safety valve test logs.' },
      { id: 'doc_blr_2', code: 'STEAM_PIPING', name: 'Steam Pipeline Stress Analysis & Isometric Drawing', required: true, format: 'PDF', description: 'Detailed layout showing thermal expansion loops, steam traps, and blowdown discharge vessels.' },
    ],
  },
  {
    id: 'app_dg_emission',
    code: 'DG_SET_EMISSION_NOC',
    name: 'Standby DG Set Acoustic Enclosure & Air Emission Compliance NOC',
    title: 'Standby DG Set Acoustic Enclosure & Air Emission Compliance NOC',
    authority: 'State Pollution Control Board (SPCB / PCC) / CPCB',
    issuingAuthority: 'State Pollution Control Board (SPCB / PCC) / CPCB',
    category: 'Environmental & Pollution',
    portalName: 'State SPCB Air Pollution Control Division',
    level: 'State',
    stage: 'pre_construction',
    slaDays: 20,
    demoProcessingTime: '20 Working Days (Demo SLA)',
    risk: 'low',
    estimatedFeeInr: 12000,
    description:
      'Clearance certifying compliance of standby diesel generating sets with noise emission limits (<75 dB(A) at 1m) and minimum statutory chimney stack height.',
    legalBasis: 'Environment (Protection) Rules, 1986 - Emission & Noise Standards for DG Sets',
    whyApplicable: 'Mandatory for industrial units deploying standby diesel generators to ensure compliance with noise and air emission norms.',
    applicabilityReason: 'Mandatory for industrial units deploying standby diesel generators to ensure compliance with noise and air emission norms.',
    dependencies: ['SPCB_CTE'],
    prerequisites: ['SPCB_CTE'],
    isCriticalPath: false,
    nextAction: 'Verify physical chimney stack height meets statutory formula (H = h + 0.2*sqrt(kVA)) and submit manufacturer type-approval certificate.',
    requiredDocuments: [
      { id: 'doc_dg_1', code: 'TYPE_APPROVAL', name: 'CPCB Type Approval & Conformity of Production (COP) Certificate', required: true, format: 'PDF', description: 'Engine manufacturer emissions test certificate approved by ARAI / ICAT.' },
      { id: 'doc_dg_2', code: 'ACOUSTIC_CERT', name: 'Acoustic Enclosure Insertion Loss Test Certificate', required: true, format: 'PDF', description: 'Sound attenuation report demonstrating insertion loss of minimum 25 dB(A).' },
    ],
  },
  {
    id: 'app_plastic_epr',
    code: 'PLASTIC_PACKAGING_EPR',
    name: 'Extended Producer Responsibility (EPR) for Plastic Packaging',
    title: 'Extended Producer Responsibility (EPR) for Plastic Packaging',
    authority: 'Central Pollution Control Board (CPCB National EPR Portal)',
    issuingAuthority: 'Central Pollution Control Board (CPCB National EPR Portal)',
    category: 'Environmental & Pollution',
    portalName: 'CPCB National EPR Portal for Plastic Packaging',
    level: 'Central',
    stage: 'pre_operation',
    slaDays: 30,
    demoProcessingTime: '30 Working Days (Demo SLA)',
    risk: 'medium',
    estimatedFeeInr: 15000,
    description:
      'Statutory EPR registration for Brand Owners (PIBOs) and food packaging manufacturers utilizing Category-II flexible or multi-layered plastic films.',
    legalBasis: 'Plastic Waste Management Rules, 2016 (as amended)',
    whyApplicable: 'Mandatory under Plastic Waste Management Rules for commercial entities introducing plastic packaging pouches or laminates into consumer market.',
    applicabilityReason: 'Mandatory under Plastic Waste Management Rules for commercial entities introducing plastic packaging pouches or laminates into consumer market.',
    dependencies: ['SIDC_LAND_ALLOTMENT'],
    prerequisites: ['SIDC_LAND_ALLOTMENT'],
    isCriticalPath: false,
    nextAction: 'Register company profile on CPCB National EPR portal with annual plastic procurement forecast and tie-up with registered plastic waste processor.',
    requiredDocuments: [
      { id: 'doc_epr_1', code: 'PLASTIC_AUDIT', name: 'Annual Plastic Packaging Procurement & Usage Plan', required: true, format: 'PDF', description: 'Breakdown of Category-I, II, and III plastic grades with target recycling obligations.' },
      { id: 'doc_epr_2', code: 'PROCESSOR_MOU', name: 'Agreement with Registered Plastic Waste Processor (PWPF)', required: true, format: 'PDF', description: 'Formal contract for post-consumer plastic collection and recycling certificates.' },
    ],
  },
  {
    id: 'app_legal_metrology',
    code: 'LEGAL_METROLOGY_PACKAGED',
    name: 'Legal Metrology (Packaged Commodities) Manufacturer Registration',
    title: 'Legal Metrology (Packaged Commodities) Manufacturer Registration',
    authority: 'Department of Legal Metrology / Consumer Affairs Dept',
    issuingAuthority: 'Department of Legal Metrology / Consumer Affairs Dept',
    category: 'Industry & Operational Standards',
    portalName: 'e-Maap State Legal Metrology Portal',
    level: 'State',
    stage: 'pre_operation',
    slaDays: 20,
    demoProcessingTime: '20 Working Days (Demo SLA)',
    risk: 'low',
    estimatedFeeInr: 8000,
    description:
      'Registration under Rule 27 of Legal Metrology (Packaged Commodities) Rules 2011 for commercial packaging, labeling, and net-quantity declaration.',
    legalBasis: 'Legal Metrology Act 2009 & Legal Metrology (Packaged Commodities) Rules 2011',
    whyApplicable: 'Mandatory for any manufacturing unit packing consumer commodities in pre-sealed bottles, bags, cartons, or pouches.',
    applicabilityReason: 'Mandatory for any manufacturing unit packing consumer commodities in pre-sealed bottles, bags, cartons, or pouches.',
    dependencies: ['SIDC_LAND_ALLOTMENT'],
    prerequisites: ['SIDC_LAND_ALLOTMENT'],
    isCriticalPath: false,
    nextAction: 'Submit specimen product label artwork showing font size, MRP, net quantity, manufacturing date, and customer care details.',
    requiredDocuments: [
      { id: 'doc_lm_1', code: 'LABEL_SPECIMEN', name: 'Specimen Label Artwork & Mandatory Declarations Draft', required: true, format: 'PDF', description: 'Conforming to mandatory declaration norms (MRP, Net Weight, Manufacturer Details).' },
      { id: 'doc_lm_2', code: 'SCALE_STAMPING', name: 'Weighing Scale & Flow Filling Machine Verification Certificates', required: true, format: 'PDF', description: 'Annual calibration stamping certificate from Legal Metrology Inspector.' },
    ],
  },
  {
    id: 'app_fssai_lic',
    code: 'FSSAI_CENTRAL_LIC',
    name: 'FSSAI Central Food Safety Manufacturing License',
    title: 'FSSAI Central Food Safety Manufacturing License',
    authority: 'Food Safety and Standards Authority of India (FSSAI)',
    issuingAuthority: 'Food Safety and Standards Authority of India (FSSAI)',
    category: 'Industry & Operational Standards',
    portalName: 'FoSCoS (Food Safety Compliance System)',
    level: 'Central',
    stage: 'pre_operation',
    slaDays: 30,
    demoProcessingTime: '30 Working Days (Demo SLA)',
    risk: 'high',
    estimatedFeeInr: 10000,
    description:
      'Statutory food business operating license for commercial food manufacturing, processing, and packaging facilities under Food Safety and Standards Act 2006.',
    legalBasis: 'Food Safety and Standards (Licensing and Registration) Regulations, 2011',
    whyApplicable: 'Mandatory statutory license for all food processing, beverage bottling, and packaged food manufacturing operations.',
    applicabilityReason: 'Mandatory statutory license for all food processing, beverage bottling, and packaged food manufacturing operations.',
    dependencies: ['SIDC_LAND_ALLOTMENT', 'SPCB_CTE'],
    prerequisites: ['SIDC_LAND_ALLOTMENT', 'SPCB_CTE'],
    isCriticalPath: true,
    nextAction: 'Upload NABL-certified potable water chemical & microbiological testing report and FSMS hygiene plan on FoSCoS portal.',
    requiredDocuments: [
      { id: 'doc_fssai_1', code: 'FOOD_SAFETY_PLAN', name: 'FSMS (Food Safety Management System) Plan & SOPs', required: true, format: 'PDF', description: 'HACCP hazard analysis, allergen segregation plan, and clean-in-place (CIP) SOPs.' },
      { id: 'doc_fssai_2', code: 'WATER_TEST', name: 'Potable Water Testing Report from NABL Accredited Lab', required: true, format: 'PDF', description: 'Comprehensive potable water test certificate conforming to IS 10500 standards.' },
      { id: 'doc_fssai_3', code: 'RECALL_PLAN', name: 'Product Recall Protocol & Technical Personnel Qualification Proof', required: true, format: 'PDF', description: 'Degree certificates of food technologists and mock recall procedure.' },
    ],
  },
  {
    id: 'app_peso_lic',
    code: 'PESO_EXPLOSIVES_LIC',
    name: 'PESO Bulk Solvent & Flammable Storage License',
    title: 'PESO Bulk Solvent & Flammable Storage License',
    authority: 'Petroleum and Explosives Safety Organisation (PESO), Ministry of Commerce & Industry',
    issuingAuthority: 'Petroleum and Explosives Safety Organisation (PESO), Ministry of Commerce & Industry',
    category: 'Safety, Fire & Labour',
    portalName: 'PESO Online Application Portal',
    level: 'Central',
    stage: 'pre_operation',
    slaDays: 45,
    demoProcessingTime: '45 Working Days (Demo SLA)',
    risk: 'high',
    estimatedFeeInr: 40000,
    description:
      'Statutory license for bulk storage of Class A/B/C petroleum products, organic chemical solvents, pressurized gases, and bulk diesel storage.',
    legalBasis: 'Petroleum Act 1934, Petroleum Rules 2002 & Gas Cylinder Rules',
    whyApplicable: 'Mandatory when bulk inflammable solvents, class A/B petroleum (>2500L), or flammable industrial gases are stored.',
    applicabilityReason: 'Mandatory when bulk inflammable solvents, class A/B petroleum (>2500L), or flammable industrial gases are stored.',
    dependencies: ['SIDC_LAND_ALLOTMENT', 'FIRE_NOC_PROVISIONAL', 'SPCB_CTE'],
    prerequisites: ['SIDC_LAND_ALLOTMENT', 'FIRE_NOC_PROVISIONAL', 'SPCB_CTE'],
    isCriticalPath: false,
    nextAction: 'Submit tank fabrication drawings with CIMFR flameproof electrical certificates and dyke wall containment volume calculations.',
    requiredDocuments: [
      { id: 'doc_peso_1', code: 'TANK_FAB', name: 'Aboveground / Underground Tank Fabrication Drawings', required: true, format: 'PDF', description: 'Vessel design codes with dyke wall volume calculations certified by PESO competent person.' },
      { id: 'doc_peso_2', code: 'FLAMEPROOF_CERT', name: 'Flameproof Electrical Equipment (FLP/Ex-d) Test Certificates', required: true, format: 'PDF', description: 'CIMFR testing certificates for motors, lighting, and fittings in hazardous zone.' },
    ],
  },
  {
    id: 'app_fire_final',
    code: 'FIRE_NOC_FINAL',
    name: 'Final Fire Safety Occupancy Certificate (Final NOC)',
    title: 'Final Fire Safety Occupancy Certificate (Final NOC)',
    authority: 'State Fire and Emergency Services Directorate / Local Fire Brigade',
    issuingAuthority: 'State Fire and Emergency Services Directorate / Local Fire Brigade',
    category: 'Safety, Fire & Labour',
    portalName: 'State Fire Clearance Cell',
    level: 'State',
    stage: 'pre_operation',
    slaDays: 20,
    demoProcessingTime: '20 Working Days (Demo SLA)',
    risk: 'medium',
    estimatedFeeInr: 15000,
    description:
      'On-site physical inspection and hydraulic pressure testing of operating fire alarm networks, yard hydrants, automatic sprinklers, and emergency evacuation drills.',
    legalBasis: 'State Fire Prevention and Life Safety Measures Act',
    whyApplicable: 'Mandatory to obtain before commercial occupation and before Factory License issuance.',
    applicabilityReason: 'Mandatory to obtain before commercial occupation and before Factory License issuance.',
    dependencies: ['FIRE_NOC_PROVISIONAL'],
    prerequisites: ['FIRE_NOC_PROVISIONAL'],
    isCriticalPath: true,
    nextAction: 'Schedule on-site physical fire drill demonstration and static pressure test (3.5 bar nozzle pressure) with Local Fire Officer.',
    requiredDocuments: [
      { id: 'doc_fire_fin_1', code: 'COMMISSIONING_RPT', name: 'Fire Hydrant & Sprinkler Commissioning Test Report', required: true, format: 'PDF', description: 'Signed by licensed fire contractor certifying 900 LPM pump flow and working pressures.' },
      { id: 'doc_fire_fin_2', code: 'TRAINING_LOG', name: 'Employee Fire Fighting & Evacuation Drill Log', required: true, format: 'PDF', description: 'Roster of certified fire marshals with training photographs.' },
    ],
  },
  {
    id: 'app_spcb_cto',
    code: 'SPCB_CTO',
    name: 'Consent to Operate (CTO) & Trade Effluent Discharge Permit',
    title: 'Consent to Operate (CTO) & Trade Effluent Discharge Permit',
    authority: 'State Pollution Control Board (SPCB / PCC)',
    issuingAuthority: 'State Pollution Control Board (SPCB / PCC)',
    category: 'Environmental & Pollution',
    portalName: 'OCMMS Online Portal',
    level: 'State',
    stage: 'pre_operation',
    slaDays: 45,
    demoProcessingTime: '45 Working Days (Demo SLA)',
    risk: 'high',
    estimatedFeeInr: 95000,
    description:
      'Operating consent issued after SPCB Regional Officer physical inspection verifying installed ETP, STP, flow meters, online continuous emission monitors, and solid waste storage.',
    legalBasis: 'Section 25 Water Act 1974, Section 21 Air Act 1981 & Hazardous Waste Rules',
    whyApplicable: 'Mandatory to initiate trial runs and commercial manufacture for Red, Orange, and Green units.',
    applicabilityReason: 'Mandatory to initiate trial runs and commercial manufacture for Red, Orange, and Green units.',
    dependencies: ['SPCB_CTE', 'FIRE_NOC_FINAL'],
    prerequisites: ['SPCB_CTE', 'FIRE_NOC_FINAL'],
    isCriticalPath: true,
    nextAction: 'Complete civil construction of captive ETP and submit point-by-point CTE compliance report for SPCB field verification.',
    requiredDocuments: [
      { id: 'doc_cto_1', code: 'CTE_COMPLIANCE', name: 'Point-to-Point CTE Condition Compliance Report', required: true, format: 'PDF', description: 'Photographic evidence and test certificates of completed ETP, acoustic enclosures, and APCE.' },
      { id: 'doc_cto_2', code: 'ETP_COMMISSION', name: 'ETP Treated Water Analysis Report from MoEF Lab', required: true, format: 'PDF', description: 'Independent laboratory analysis verifying treated effluent complies with discharge norms.' },
    ],
  },
  {
    id: 'app_factory_lic',
    code: 'FACTORY_LICENSE',
    name: 'Final Factory License & Registration of Manufacturing Unit (Form 4)',
    title: 'Final Factory License & Registration of Manufacturing Unit (Form 4)',
    authority: 'Directorate of Industrial Safety and Health (DISH) / Chief Inspector of Factories',
    issuingAuthority: 'Directorate of Industrial Safety and Health (DISH) / Chief Inspector of Factories',
    category: 'Safety, Fire & Labour',
    portalName: 'State Labour & Factories Portal',
    level: 'State',
    stage: 'pre_operation',
    slaDays: 30,
    demoProcessingTime: '30 Working Days (Demo SLA)',
    risk: 'high',
    estimatedFeeInr: 25000,
    description:
      'Grant of Form 4 Factory License authorising physical employment of industrial workers and commercial manufacturing operations.',
    legalBasis: 'The Factories Act, 1948 - Section 6 & 7',
    whyApplicable: 'Mandatory before commencement of commercial manufacturing.',
    applicabilityReason: 'Mandatory before commencement of commercial manufacturing.',
    dependencies: ['FACTORY_PLAN_APPROVAL', 'SPCB_CTO', 'FIRE_NOC_FINAL'],
    prerequisites: ['FACTORY_PLAN_APPROVAL', 'SPCB_CTO', 'FIRE_NOC_FINAL'],
    isCriticalPath: true,
    nextAction: 'Obtain Form 1A Structural Stability Certificate signed by chartered civil engineer and submit final Form 2 notice.',
    requiredDocuments: [
      { id: 'doc_lic_1', code: 'STABILITY_CERT', name: 'Building Structural Stability Certificate (Form 1A)', required: true, format: 'PDF', description: 'Endorsed by chartered structural engineer confirming load ratings and crane gantry safety.' },
      { id: 'doc_lic_2', code: 'COMPENSATION_POLICY', name: 'Workers Compensation Insurance / ESIC Code Confirmation', required: true, format: 'PDF', description: 'Proof of statutory social security coverage for all permanent and contract workforce.' },
    ],
  },
  {
    id: 'app_esic_epfo',
    code: 'ESIC_EPFO_REGISTRATION',
    name: 'ESIC & EPFO Mandatory Social Security Registration',
    title: 'ESIC & EPFO Mandatory Social Security Registration',
    authority: 'Employees\' Provident Fund Organisation (EPFO) & ESIC',
    issuingAuthority: 'Employees\' Provident Fund Organisation (EPFO) & ESIC',
    category: 'Safety, Fire & Labour',
    portalName: 'Shram Suvidha Unified Portal',
    level: 'Central',
    stage: 'pre_establishment',
    slaDays: 7,
    demoProcessingTime: '7 Working Days (Demo SLA)',
    risk: 'low',
    estimatedFeeInr: 5000,
    description:
      'Statutory employee welfare registrations under Employees\' Provident Funds & Miscellaneous Provisions Act 1952 and ESI Act 1948.',
    legalBasis: 'EPF & MP Act 1952 & Employees\' State Insurance Act 1948',
    whyApplicable: 'Mandatory statutory social security coverage for any enterprise employing 20 or more staff.',
    applicabilityReason: 'Mandatory statutory social security coverage for any enterprise employing 20 or more staff.',
    dependencies: ['SIDC_LAND_ALLOTMENT'],
    prerequisites: ['SIDC_LAND_ALLOTMENT'],
    isCriticalPath: false,
    nextAction: 'Maintain online electronic monthly challans (ECR) for employee wage registers and provident fund contributions.',
    requiredDocuments: [
      { id: 'doc_epf_1', code: 'EPF_DOCS', name: 'Specimen Signature Card & List of Directors', required: true, format: 'PDF', description: 'Corporate KYC and digital signature certificate of authorised signatory.' },
    ],
  },
  {
    id: 'app_nsws_reg',
    code: 'NSWS_COMPOSITE_REGISTRATION',
    name: 'National Single Window System (NSWS) Composite Industrial Filing',
    title: 'National Single Window System (NSWS) Composite Industrial Filing',
    authority: 'Department for Promotion of Industry and Internal Trade (DPIIT) / Invest India',
    issuingAuthority: 'Department for Promotion of Industry and Internal Trade (DPIIT) / Invest India',
    category: 'Taxation, Trade & Identity',
    portalName: 'National Single Window System (NSWS)',
    level: 'Central',
    stage: 'pre_establishment',
    slaDays: 3,
    demoProcessingTime: '3 Working Days (Demo SLA)',
    risk: 'low',
    estimatedFeeInr: 2000,
    description:
      'Unified Common Application Form (CAF) filing providing centralized clearance tracking across 32 Central Ministries and 27 State Single Windows.',
    legalBasis: 'DPIIT Single Window Clearance Initiative & Business Reform Action Plan (BRAP)',
    whyApplicable: 'Master investor registration linking state line departments with centralized tracking ID.',
    applicabilityReason: 'Master investor registration linking state line departments with centralized tracking ID.',
    dependencies: [],
    prerequisites: [],
    isCriticalPath: false,
    nextAction: 'Keep central investor profile updated and synchronize state application tracking numbers with NSWS dashboard.',
    requiredDocuments: [
      { id: 'doc_nsws_1', code: 'CAF_DOC', name: 'Unified Common Application Form (CAF)', required: true, format: 'PDF', description: 'Consolidated investor dossier with PAN, CIN, and authorized signatory DSC.' },
    ],
  },
];

export const STANDARD_DEPENDENCY_EDGES: ApprovalDependencyEdge[] = [
  { from: 'SIDC_LAND_ALLOTMENT', to: 'NON_AGRI_CONVERSION', type: 'hard_prerequisite', label: 'Land allotment replaces NA conversion' },
  { from: 'SIDC_LAND_ALLOTMENT', to: 'MOEF_EC', type: 'hard_prerequisite', label: 'Possession required for EIA boundaries' },
  { from: 'SIDC_LAND_ALLOTMENT', to: 'SPCB_CTE', type: 'hard_prerequisite', label: 'Land title needed for pollution consent' },
  { from: 'SIDC_LAND_ALLOTMENT', to: 'CGWA_GROUNDWATER_NOC', type: 'hard_prerequisite', label: 'Cadastral survey for aquifer verification' },
  { from: 'SIDC_LAND_ALLOTMENT', to: 'DISCOM_POWER_SANCTION', type: 'hard_prerequisite', label: 'Premises ownership for HT line route' },
  { from: 'SIDC_LAND_ALLOTMENT', to: 'WATER_SUPPLY_SANCTION', type: 'hard_prerequisite', label: 'Site demarcation for pipeline connection' },
  { from: 'MOEF_EC', to: 'SPCB_CTE', type: 'hard_prerequisite', label: 'EC conditions must be mirrored in CTE' },
  { from: 'SPCB_CTE', to: 'FIRE_NOC_PROVISIONAL', type: 'hard_prerequisite', label: 'Environmental layout cleared prior to fire sanction' },
  { from: 'SPCB_CTE', to: 'FACTORY_PLAN_APPROVAL', type: 'hard_prerequisite', label: 'Pollution boundaries determine machine layouts' },
  { from: 'FIRE_NOC_PROVISIONAL', to: 'FACTORY_PLAN_APPROVAL', type: 'hard_prerequisite', label: 'Fire exits incorporated into factory plan' },
  { from: 'FIRE_NOC_PROVISIONAL', to: 'FIRE_NOC_FINAL', type: 'hard_prerequisite', label: 'Physical execution must match provisional plan' },
  { from: 'DISCOM_POWER_SANCTION', to: 'CEIG_ELECTRICAL_APPROVAL', type: 'hard_prerequisite', label: 'Load sanction required prior to CEIG inspection' },
  { from: 'SPCB_CTE', to: 'BOILER_REGISTRATION', type: 'hard_prerequisite', label: 'Air chimney heights fixed in CTE' },
  { from: 'SPCB_CTE', to: 'DG_SET_EMISSION_NOC', type: 'hard_prerequisite', label: 'Air emission stack heights verified in CTE' },
  { from: 'FIRE_NOC_PROVISIONAL', to: 'PESO_EXPLOSIVES_LIC', type: 'hard_prerequisite', label: 'Fire clearance mandatory for PESO storage' },
  { from: 'SPCB_CTE', to: 'FSSAI_CENTRAL_LIC', type: 'hard_prerequisite', label: 'Pollution consent needed for FoSCoS license' },
  { from: 'SPCB_CTE', to: 'SPCB_CTO', type: 'hard_prerequisite', label: 'Civil construction & ETP readiness checked against CTE' },
  { from: 'FIRE_NOC_FINAL', to: 'SPCB_CTO', type: 'recommended_parallel', label: 'Life safety clearances checked before operating consent' },
  { from: 'SPCB_CTO', to: 'FACTORY_LICENSE', type: 'hard_prerequisite', label: 'Operating consent mandatory before factory licensing' },
  { from: 'FACTORY_PLAN_APPROVAL', to: 'FACTORY_LICENSE', type: 'hard_prerequisite', label: 'Final license checks adherence to approved layout' },
  { from: 'FIRE_NOC_FINAL', to: 'FACTORY_LICENSE', type: 'hard_prerequisite', label: 'Fire signoff mandatory for labour deployment' },
  { from: 'FSSAI_CENTRAL_LIC', to: 'FACTORY_LICENSE', type: 'recommended_parallel', label: 'Food safety authorization before commercial packing' },
];
