import { DemonstrationScheme } from '../../types/index.js';

export const DEMONSTRATION_SCHEMES: DemonstrationScheme[] = [
  {
    id: 'demo_scheme_mh_psi',
    name: 'Maharashtra Package Scheme of Incentives (PSI 2019 / 2024)',
    shortName: 'Maharashtra PSI Industrial Incentive',
    sponsoringBody: 'Directorate of Industries, Department of Industries, Government of Maharashtra',
    level: 'State',
    applicableStates: ['Maharashtra'],
    applicableIndustries: ['all'],
    applicableProjectTypes: [
      'Greenfield Manufacturing Unit',
      'Greenfield / New Unit',
      'New Unit',
      'Expansion',
      'Modernization',
    ],
    minInvestmentInrCrores: 5.0,
    maxInvestmentInrCrores: 1000.0,
    applicableBusinessTypes: [
      'Private Limited Company',
      'Public Limited Company',
      'Limited Liability Partnership (LLP)',
      'MSME / Udyam Enterprise',
      'Partnership Firm',
    ],
    benefitType: 'Tax & Duty Exemption',
    maxBenefit: 'Up to 80% Gross SGST Reimbursement for 7–10 Years + 100% Stamp Duty Waiver',
    description:
      'A comprehensive flagship state fiscal framework granting capital subsidies, electricity duty waivers, and State GST reimbursements to eligible manufacturing undertakings located in backward, developing (Taluka Category B/C/D/D+), and MIDC industrial estates.',
    keyBenefits: [
      'Industrial Promotion Subsidy: 50% to 80% reimbursement of eligible State GST paid for 7 to 10 years',
      '100% exemption from payment of Stamp Duty on land purchase, lease deed, and loan mortgage execution',
      'Exemption from electricity duty for 7 years and industrial power tariff rebate of ₹1.50/unit in developing zones',
      '5% interest subsidy on term loans for MSMEs and clean green technology infrastructure',
    ],
    eligibilityConditions: [
      'Unit must be situated in Maharashtra on certified MIDC land or authorized private industrial zoning',
      'Fixed capital investment must be made in eligible plant, machinery, and factory premises with bank disbursement audit',
      'Fulfillment of minimum 80% local employment quota in accordance with the Maharashtra Industrial Policy',
      'Timely commercial commissioning within the approved investment period',
    ],
    requiredDocuments: [
      {
        id: 'doc_dpr_psi',
        name: 'Detailed Project Report (DPR) with Capital Outlay Schedule',
        description: 'Comprehensive project report detailing machinery specs, capacity, and itemized capital costs.',
        mandatory: true,
        matchingDocCode: 'DOC_DPR',
      },
      {
        id: 'doc_land_psi',
        name: 'MIDC Land Possession Order / Registered Lease Deed',
        description: 'Proof of industrial plot possession and demarcation coordinates.',
        mandatory: true,
        matchingDocCode: 'DOC_LAND_ALLOTMENT',
      },
      {
        id: 'doc_cte_psi',
        name: 'MPCB Consent to Establish (CTE) / Pollution Clearance',
        description: 'Valid pollution control board clearance for proposed capacity.',
        mandatory: true,
        matchingDocCode: 'DOC_SPCB_CTE',
      },
      {
        id: 'doc_fin_psi',
        name: 'Audited Financial Statements & CA Net Worth Certificate',
        description: 'Chartered Accountant certified project cost breakdown and net worth documentation.',
        mandatory: true,
        matchingDocCode: 'DOC_FINANCIALS',
      },
      {
        id: 'doc_power_psi',
        name: 'MSEDCL / DISCOM Power Load Sanction Letter',
        description: 'Connected load sanction for industrial processing capacity.',
        mandatory: true,
        matchingDocCode: 'DOC_DISCOM_SANCTION',
      },
      {
        id: 'doc_incorp_psi',
        name: 'Certificate of Incorporation / Udyam Registration',
        description: 'Ministry of Corporate Affairs CIN / MSME Udyam verification certificate.',
        mandatory: true,
        matchingDocCode: 'DOC_UDYAM_CIN',
      },
    ],
    requiredClearances: ['SIDC_LAND_ALLOTMENT', 'SPCB_CTE', 'DISCOM_POWER_SANCTION'],
    officialPortal: 'https://di.maharashtra.gov.in',
    nodalAgency: 'District Industries Centre (DIC) / Directorate of Industries, Mumbai',
    isDemonstration: true,
  },
  {
    id: 'demo_scheme_pli_pharma',
    name: 'Production Linked Incentive (PLI) Scheme for Key Starting Materials (KSMs) / Active Pharmaceutical Ingredients (APIs)',
    shortName: 'Central Pharma & API PLI',
    sponsoringBody: 'Department of Pharmaceuticals, Ministry of Chemicals and Fertilizers, Government of India',
    level: 'Central',
    applicableIndustries: ['pharma', 'chemicals'],
    applicableProjectTypes: [
      'Greenfield Manufacturing Unit',
      'Greenfield / New Unit',
      'New Unit',
      'Expansion',
    ],
    minInvestmentInrCrores: 20.0,
    maxInvestmentInrCrores: 500.0,
    applicableBusinessTypes: [
      'Private Limited Company',
      'Public Limited Company',
      'Limited Liability Partnership (LLP)',
    ],
    benefitType: 'Production Linked Incentive',
    maxBenefit: '5% to 20% Financial Incentive on Incremental Sales (Max ₹1,000 Cr envelope)',
    description:
      'National flagship scheme dedicated to achieving self-reliance and domestic manufacturing sovereignty in identified 41 critical Key Starting Materials, Drug Intermediates, and Active Pharmaceutical Ingredients (APIs).',
    keyBenefits: [
      'Direct fiscal incentive of 5% to 20% on net incremental sales for 6 consecutive financial years',
      'Priority allotment and common effluent treatment plant access in designated Bulk Drug Parks',
      'Fast-track MoEF&CC environmental clearance and inter-ministerial single window facilitation',
    ],
    eligibilityConditions: [
      'Manufacturing must strictly produce identified 41 critical KSMs/APIs (fermentation or chemical synthesis)',
      'Minimum committed cumulative investment threshold of ₹20 Cr to ₹50 Cr achieved within target gestation',
      'Greenfield industrial facility with dedicated production lines and verified banking trail',
    ],
    requiredDocuments: [
      {
        id: 'doc_pli_dpr',
        name: 'Technical Feasibility Report & Production Line Schematics',
        description: 'Certified breakdown of API synthetic chemistry, mass balance, and annual capacity.',
        mandatory: true,
        matchingDocCode: 'DOC_DPR',
      },
      {
        id: 'doc_pli_moef',
        name: 'MoEF&CC Environmental Clearance (EC) / Category Approval',
        description: 'Prior Environmental Clearance for synthetic organic chemical synthesis.',
        mandatory: true,
        matchingDocCode: 'DOC_MOEF_EC',
      },
      {
        id: 'doc_pli_cte',
        name: 'State Pollution Control Board Consent to Establish (CTE)',
        description: 'Validated Consent to Establish order with Zero Liquid Discharge (ZLD) conditions.',
        mandatory: true,
        matchingDocCode: 'DOC_SPCB_CTE',
      },
      {
        id: 'doc_pli_bank',
        name: 'Bank Financial Closure & Term Loan Sanction Letter',
        description: 'Scheduled commercial bank letter confirming debt and equity funding closure.',
        mandatory: true,
      },
      {
        id: 'doc_pli_ca',
        name: 'Statutory Auditor Cumulative Investment Commitment Certificate',
        description: 'Audit statement showing committed capital expenditure timeline.',
        mandatory: true,
      },
    ],
    requiredClearances: ['SIDC_LAND_ALLOTMENT', 'MOEF_EC', 'SPCB_CTE', 'FACTORY_PLAN_APPROVAL'],
    officialPortal: 'https://pharmaceuticals.gov.in/schemes',
    nodalAgency: 'Project Management Agency (IFCI Ltd. / DoP)',
    isDemonstration: true,
  },
  {
    id: 'demo_scheme_zed_msme',
    name: 'MSME Sustainable (ZED) Certification & Technology Upgradation Scheme',
    shortName: 'MSME ZED Green Certification Subsidy',
    sponsoringBody: 'Ministry of Micro, Small and Medium Enterprises (MoMSME), Government of India',
    level: 'Central',
    applicableIndustries: ['all'],
    applicableProjectTypes: [
      'Greenfield Manufacturing Unit',
      'Greenfield / New Unit',
      'New Unit',
      'Expansion',
      'Modernization',
      'Clean Tech / Green Transition',
    ],
    minInvestmentInrCrores: 0.25,
    maxInvestmentInrCrores: 50.0,
    applicableBusinessTypes: [
      'MSME / Udyam Enterprise',
      'Private Limited Company',
      'Limited Liability Partnership (LLP)',
      'Partnership Firm',
    ],
    benefitType: 'Green Technology Grant',
    maxBenefit: '80% Subsidy on Certification + Up to ₹5 Lakhs Financial Assistance for Clean Tech & ETP Upgrades',
    description:
      'Incentivizes MSMEs to manufacture with Zero Defect (in quality) and Zero Effect (on environment), granting hefty subsidies for pollution control equipment, energy audits, and green technology adoption.',
    keyBenefits: [
      'Up to 80% financial subsidy on assessment and certification costs across Bronze, Silver, and Gold tiers',
      'Direct grant of up to ₹5 Lakhs for installing pollution control equipment, energy meters, and testing tools',
      'Concession of 0.5% in bank interest rates on working capital and term loans from scheduled banks',
      'Exemption from earnest money deposit (EMD) and tender fees in public procurement tenders',
    ],
    eligibilityConditions: [
      'Enterprise must possess a valid Udyam Registration certificate in manufacturing category',
      'Establishment must adhere to baseline statutory environmental and labor safety norms',
      'Undertake prescribed online learning assessment and third-party desktop audit',
    ],
    requiredDocuments: [
      {
        id: 'doc_zed_udyam',
        name: 'Valid Udyam Registration Certificate',
        description: 'Official Ministry of MSME registration certificate verifying enterprise scale.',
        mandatory: true,
        matchingDocCode: 'DOC_UDYAM_CIN',
      },
      {
        id: 'doc_zed_spcb',
        name: 'SPCB Consent to Establish (CTE) / Valid Pollution Consent',
        description: 'State pollution control board operating or establishment consent.',
        mandatory: true,
        matchingDocCode: 'DOC_SPCB_CTE',
      },
      {
        id: 'doc_zed_audit',
        name: 'Baseline Energy & Environmental Audit Report',
        description: 'Initial assessment report for effluent management and electrical efficiency.',
        mandatory: false,
      },
      {
        id: 'doc_zed_quotes',
        name: 'Vendor Quotations / Invoices for Clean Tech Equipment',
        description: 'Proforma invoices for testing instruments or pollution mitigation apparatus.',
        mandatory: false,
      },
    ],
    requiredClearances: ['SPCB_CTE'],
    officialPortal: 'https://zed.msme.gov.in',
    nodalAgency: 'Quality Council of India (QCI) & National Productivity Council',
    isDemonstration: true,
  },
  {
    id: 'demo_scheme_specs_electronics',
    name: 'Scheme for Promotion of Manufacturing of Electronic Components and Semiconductors (SPECS)',
    shortName: 'SPECS Electronics & Component Subsidy',
    sponsoringBody: 'Ministry of Electronics and Information Technology (MeitY), Government of India',
    level: 'Central',
    applicableIndustries: ['electronics', 'metallurgy', 'renewable_energy'],
    applicableProjectTypes: [
      'Greenfield Manufacturing Unit',
      'Greenfield / New Unit',
      'New Unit',
      'Expansion',
    ],
    minInvestmentInrCrores: 5.0,
    maxInvestmentInrCrores: 1000.0,
    applicableBusinessTypes: [
      'Private Limited Company',
      'Public Limited Company',
      'Limited Liability Partnership (LLP)',
      'Joint Venture',
    ],
    benefitType: 'Capital Subsidy',
    maxBenefit: '25% Financial Reimbursement on Capital Expenditure for Plant, Machinery & Clean Rooms',
    description:
      'Provides a direct 25% financial incentive on capital expenditure for plant, machinery, clean room utilities, and equipment for manufacturing active/passive electronic components, printed circuit boards, and semiconductor packaging.',
    keyBenefits: [
      '25% reimbursement on capital expenditure for plant, specialized clean rooms, and test utilities',
      'Zero customs duty concessions on capital machinery imports under Project Import Regulations',
      'Preferred consideration for industrial land allotment in Electronics Manufacturing Clusters (EMCs)',
    ],
    eligibilityConditions: [
      'Manufacturing unit producing eligible electronic goods, components, or semiconductor packaging lines',
      'Minimum threshold investment of ₹5 Cr to ₹1,000 Cr depending on the specific component classification',
      'Commercial production commencement within committed 5-year investment window',
    ],
    requiredDocuments: [
      {
        id: 'doc_specs_dpr',
        name: 'Detailed Project Report (DPR) with Clean Room Engineering Layout',
        description: 'Technical specs, ISO class clean room details, and equipment vendor proformas.',
        mandatory: true,
        matchingDocCode: 'DOC_DPR',
      },
      {
        id: 'doc_specs_land',
        name: 'Industrial Land Allotment Order / Title Deed',
        description: 'Plot possession or verified registered lease deed in industrial park or EMC.',
        mandatory: true,
        matchingDocCode: 'DOC_LAND_ALLOTMENT',
      },
      {
        id: 'doc_specs_cte',
        name: 'State Pollution Control Board Consent to Establish (CTE)',
        description: 'Pollution board clearance for electronic component fabrication.',
        mandatory: true,
        matchingDocCode: 'DOC_SPCB_CTE',
      },
      {
        id: 'doc_specs_power',
        name: 'High Tension (HT) Power Allocation Sanction',
        description: 'Uninterrupted dual-source grid connectivity sanction from state utility.',
        mandatory: true,
        matchingDocCode: 'DOC_DISCOM_SANCTION',
      },
      {
        id: 'doc_specs_audit',
        name: 'Statutory Auditor Net Worth & Banking Solvency Dossier',
        description: 'Certified financial solvency report verifying equity capability.',
        mandatory: true,
      },
    ],
    requiredClearances: ['SIDC_LAND_ALLOTMENT', 'SPCB_CTE', 'DISCOM_POWER_SANCTION'],
    officialPortal: 'https://www.meity.gov.in/esdm/specs',
    nodalAgency: 'Industrial Finance Corporation of India (IFCI) / MeitY',
    isDemonstration: true,
  },
  {
    id: 'demo_scheme_pmfme_food',
    name: 'Prime Minister Formalisation of Micro food processing Enterprises (PMFME) Scheme',
    shortName: 'PMFME Agro & Food Credit Subsidy',
    sponsoringBody: 'Ministry of Food Processing Industries (MoFPI) & State Directorate of Industries',
    level: 'Central',
    applicableIndustries: ['food_processing'],
    applicableProjectTypes: [
      'Greenfield Manufacturing Unit',
      'Greenfield / New Unit',
      'New Unit',
      'Expansion',
      'Modernization',
    ],
    minInvestmentInrCrores: 0.1,
    maxInvestmentInrCrores: 10.0,
    applicableBusinessTypes: [
      'MSME / Udyam Enterprise',
      'Proprietorship',
      'Partnership Firm',
      'Private Limited Company',
    ],
    benefitType: 'Capital Subsidy',
    maxBenefit: '35% Credit-Linked Capital Subsidy up to ₹10 Lakhs + Seed Capital & Branding Grants',
    description:
      'Part of Atmanirbhar Bharat Abhiyan to integrate unorganized micro food processing units into formal supply chains, offering credit-linked capital subsidies and common facility access under One District One Product (ODOP).',
    keyBenefits: [
      '35% credit-linked capital subsidy for plant and machinery procurement (max ₹10 Lakhs per unit)',
      'Seed capital of ₹40,000 per food processing worker/member for working capital and minor tools',
      '50% grant for branding and marketing support for products adhering to ODOP standards',
      'Subsidized food testing and nutrition lab access at NIFTEM and designated state labs',
    ],
    eligibilityConditions: [
      'Micro or small food processing enterprise holding valid Udyam Registration',
      'Alignment with designated One District One Product (ODOP) agro-processing crops of the district',
      'Bank appraisal and sanction for enterprise term loan covering eligible capital expenditure',
    ],
    requiredDocuments: [
      {
        id: 'doc_pmfme_udyam',
        name: 'Udyam Registration & FSSAI Application Receipt',
        description: 'Proof of MSME registration and statutory food safety authority filing.',
        mandatory: true,
        matchingDocCode: 'DOC_UDYAM_CIN',
      },
      {
        id: 'doc_pmfme_bank',
        name: 'Bank Term Loan Sanction Letter',
        description: 'Bank appraisal confirming credit linkage under the PMFME portal.',
        mandatory: true,
      },
      {
        id: 'doc_pmfme_dpr',
        name: 'Detailed Project Report (DPR) with Machinery Invoices',
        description: 'Quotations for food grading, sorting, packaging, and processing machinery.',
        mandatory: true,
        matchingDocCode: 'DOC_DPR',
      },
      {
        id: 'doc_pmfme_land',
        name: 'Proof of Land / Processing Shed Tenancy',
        description: 'Owned industrial shed deed or minimum 7-year registered lease agreement.',
        mandatory: true,
        matchingDocCode: 'DOC_LAND_ALLOTMENT',
      },
    ],
    requiredClearances: ['SPCB_CTE'],
    officialPortal: 'https://pmfme.mofpi.gov.in',
    nodalAgency: 'State Nodal Agency (SNA) / Department of Agriculture & Agro-Industries',
    isDemonstration: true,
  },
  {
    id: 'demo_scheme_pli_auto',
    name: 'Production Linked Incentive (PLI) Scheme for Automobile & Auto Component Industry',
    shortName: 'Auto Components & EV PLI',
    sponsoringBody: 'Ministry of Heavy Industries (MHI), Government of India',
    level: 'Central',
    applicableIndustries: ['automobile', 'electronics', 'metallurgy'],
    applicableProjectTypes: [
      'Greenfield Manufacturing Unit',
      'Greenfield / New Unit',
      'New Unit',
      'Expansion',
    ],
    minInvestmentInrCrores: 25.0,
    maxInvestmentInrCrores: 1000.0,
    applicableBusinessTypes: [
      'Private Limited Company',
      'Public Limited Company',
    ],
    benefitType: 'Production Linked Incentive',
    maxBenefit: '8% to 18% Cash Incentive on Incremental Sales of Advanced Automotive Technology (AAT) Parts',
    description:
      'A ₹25,938 Crore central incentive initiative to overcome domestic cost disabilities, drive global automotive champions, and foster indigenous production of zero-emission vehicles and critical safety/powertrain assemblies.',
    keyBenefits: [
      '8% to 18% incentive on certified sales value of eligible Advanced Automotive Technology components',
      'Fast-track vehicle safety and component homologation testing at ARAI, ICAT, and GARC',
      'Additional 2% incentive kicker for components utilized in 100% battery electric vehicle platforms',
    ],
    eligibilityConditions: [
      'Manufacturing unit dedicated to certified Advanced Automotive Technology (AAT) list components',
      'Minimum cumulative new domestic investment of ₹25 Cr (component champion) or ₹250 Cr (OEM champion)',
      'Strict minimum domestic value addition (DVA) of 50% verified by testing agencies',
    ],
    requiredDocuments: [
      {
        id: 'doc_auto_dpr',
        name: 'DPR with Advanced Automotive Technology (AAT) Product Plan',
        description: 'Engineering blueprint outlining automotive components and domestic value addition.',
        mandatory: true,
        matchingDocCode: 'DOC_DPR',
      },
      {
        id: 'doc_auto_land',
        name: 'Industrial Park Land Allotment & Factory Layout Approval',
        description: 'Registered industrial plot and Directorate of Industrial Safety approved plan.',
        mandatory: true,
        matchingDocCode: 'DOC_LAND_ALLOTMENT',
      },
      {
        id: 'doc_auto_cte',
        name: 'Pollution Control Board Consent to Establish (CTE)',
        description: 'Air and Water Act clearance for precision machining and paint shop operations.',
        mandatory: true,
        matchingDocCode: 'DOC_SPCB_CTE',
      },
      {
        id: 'doc_auto_dva',
        name: 'Domestic Value Addition (DVA) Testing & Homologation Plan',
        description: 'Component architecture demonstrating minimum 50% domestic value addition.',
        mandatory: true,
      },
      {
        id: 'doc_auto_audit',
        name: 'CA Statutory Certificate of Committed Equity & Debt Infusion',
        description: 'Audited financial proof of capital readiness for automotive machinery.',
        mandatory: true,
      },
    ],
    requiredClearances: ['SIDC_LAND_ALLOTMENT', 'SPCB_CTE', 'FACTORY_PLAN_APPROVAL'],
    officialPortal: 'https://heavyindustries.gov.in',
    nodalAgency: 'Project Management Agency (IFCI) / Ministry of Heavy Industries',
    isDemonstration: true,
  },
  {
    id: 'demo_scheme_gj_ind_policy',
    name: 'Gujarat Industrial Policy - Financial Assistance for Manufacturing Undertakings',
    shortName: 'Gujarat Industrial Policy Incentive',
    sponsoringBody: 'Industries Commissionerate, Department of Energy and Petrochemicals, Government of Gujarat',
    level: 'State',
    applicableStates: ['Gujarat'],
    applicableIndustries: ['all'],
    applicableProjectTypes: [
      'Greenfield Manufacturing Unit',
      'Greenfield / New Unit',
      'New Unit',
      'Expansion',
      'Modernization',
    ],
    minInvestmentInrCrores: 2.0,
    maxInvestmentInrCrores: 500.0,
    applicableBusinessTypes: [
      'Private Limited Company',
      'Public Limited Company',
      'Limited Liability Partnership (LLP)',
      'MSME / Udyam Enterprise',
      'Partnership Firm',
    ],
    benefitType: 'Capital Subsidy',
    maxBenefit: '12% Capital Investment Subsidy (Up to ₹1.5 Cr) + 7% Interest Subsidy for 7 Years',
    description:
      'Premier state package supporting capital asset creation, cleaner production technologies, and industrial ecosystem expansion in GIDC industrial estates and special investment regions.',
    keyBenefits: [
      '12% Capital Investment Subsidy on eligible gross fixed assets (Plant & Machinery)',
      '7% interest subsidy on term loans for 7 years (maximum ₹35 Lakhs per annum)',
      '100% reimbursement of stamp duty and registration fees on industrial land purchase/lease',
      '50% financial assistance for setting up Effluent Treatment Plants (ETP) up to ₹50 Lakhs',
    ],
    eligibilityConditions: [
      'Manufacturing enterprise registered in Gujarat with GIDC plot possession or certified private industrial land',
      'Minimum investment in verified plant and machinery backed by banking transaction records',
      'Fulfillment of local employment criteria as per Gujarat State Employment Policy',
    ],
    requiredDocuments: [
      {
        id: 'doc_gj_gidc',
        name: 'GIDC Industrial Plot Allotment & Possession Receipt',
        description: 'Official Gujarat Industrial Development Corporation plot allocation order.',
        mandatory: true,
        matchingDocCode: 'DOC_LAND_ALLOTMENT',
      },
      {
        id: 'doc_gj_gpcb',
        name: 'GPCB Consent to Establish (CTE) & ETP Design Plan',
        description: 'Gujarat Pollution Control Board CTE and effluent treatment layout.',
        mandatory: true,
        matchingDocCode: 'DOC_SPCB_CTE',
      },
      {
        id: 'doc_gj_dpr',
        name: 'Detailed Project Report (DPR) with Bank Appraisal',
        description: 'Complete project cost and financial viability assessment.',
        mandatory: true,
        matchingDocCode: 'DOC_DPR',
      },
      {
        id: 'doc_gj_power',
        name: 'Gujarat DISCOM (UGVCL/DGVCL/MGVCL/PGVCL) Power Sanction',
        description: 'Connected electrical load sanction and HT substation approval.',
        mandatory: true,
        matchingDocCode: 'DOC_DISCOM_SANCTION',
      },
    ],
    requiredClearances: ['SIDC_LAND_ALLOTMENT', 'SPCB_CTE', 'DISCOM_POWER_SANCTION'],
    officialPortal: 'https://ic.gujarat.gov.in',
    nodalAgency: 'Industries Commissionerate, Gandhinagar',
    isDemonstration: true,
  },
  {
    id: 'demo_scheme_tn_ind_policy',
    name: 'Tamil Nadu Industrial Policy (TNIP) - Capital Subsidy & Electricity Tax Exemption',
    shortName: 'Tamil Nadu Industrial Package',
    sponsoringBody: 'Guidance Tamil Nadu & Department of Industries, Government of Tamil Nadu',
    level: 'State',
    applicableStates: ['Tamil Nadu'],
    applicableIndustries: ['all', 'automobile', 'electronics', 'textiles', 'chemicals'],
    applicableProjectTypes: [
      'Greenfield Manufacturing Unit',
      'Greenfield / New Unit',
      'New Unit',
      'Expansion',
    ],
    minInvestmentInrCrores: 10.0,
    maxInvestmentInrCrores: 500.0,
    applicableBusinessTypes: [
      'Private Limited Company',
      'Public Limited Company',
      'Limited Liability Partnership (LLP)',
    ],
    benefitType: 'Capital Subsidy',
    maxBenefit: 'Up to 25% Capital Subsidy + 100% Electricity Tax Exemption for 5 Years',
    description:
      'Incentivizes major manufacturing ventures across SIPCOT industrial estates and developing districts of Tamil Nadu, featuring structured capital subsidies, green infrastructure assistance, and power duty waivers.',
    keyBenefits: [
      'Investment promotion capital subsidy of 15% to 25% of eligible fixed assets in developing districts',
      '100% electricity tax exemption for 5 years from commercial commissioning',
      '50% land cost concession when establishing units in southern industrial districts',
      'Green subsidy of up to ₹1 Crore for Zero Liquid Discharge (ZLD) installations',
    ],
    eligibilityConditions: [
      'New or expanding manufacturing enterprise establishing production within Tamil Nadu',
      'Minimum committed fixed capital investment achieved within statutory 3-year window',
      'Direct formal employment generation conforming to state industrial employment guidelines',
    ],
    requiredDocuments: [
      {
        id: 'doc_tn_sipcot',
        name: 'SIPCOT Land Allotment Order / Lease Deed',
        description: 'Plot lease deed or private industrial land purchase document.',
        mandatory: true,
        matchingDocCode: 'DOC_LAND_ALLOTMENT',
      },
      {
        id: 'doc_tn_tnpcb',
        name: 'TNPCB Consent to Establish (CTE) & Air/Water NOC',
        description: 'Tamil Nadu Pollution Control Board statutory clearance.',
        mandatory: true,
        matchingDocCode: 'DOC_SPCB_CTE',
      },
      {
        id: 'doc_tn_dpr',
        name: 'Detailed Project Report (DPR) with Investment Phasing',
        description: 'Machinery schedules, factory drawings, and capital investment phasing.',
        mandatory: true,
        matchingDocCode: 'DOC_DPR',
      },
      {
        id: 'doc_tn_tangedco',
        name: 'TANGEDCO High Tension Power Sanction',
        description: 'Grid connection feasibility and load sanction from state transmission utility.',
        mandatory: true,
        matchingDocCode: 'DOC_DISCOM_SANCTION',
      },
    ],
    requiredClearances: ['SIDC_LAND_ALLOTMENT', 'SPCB_CTE', 'DISCOM_POWER_SANCTION'],
    officialPortal: 'https://investingintamilnadu.com',
    nodalAgency: 'Guidance Tamil Nadu, Chennai',
    isDemonstration: true,
  },
  {
    id: 'demo_scheme_solar_green',
    name: 'Industrial Captive Rooftop Solar & Green Power Capital Support Scheme',
    shortName: 'Captive Solar & Energy Transition Subsidy',
    sponsoringBody: 'Ministry of New and Renewable Energy (MNRE) & State Power DISCOMs',
    level: 'Central',
    applicableIndustries: ['all'],
    applicableProjectTypes: [
      'Clean Tech / Green Transition',
      'Modernization',
      'Greenfield Manufacturing Unit',
      'Greenfield / New Unit',
      'New Unit',
      'Expansion',
    ],
    minInvestmentInrCrores: 0.5,
    maxInvestmentInrCrores: 100.0,
    applicableBusinessTypes: [
      'Private Limited Company',
      'Public Limited Company',
      'Limited Liability Partnership (LLP)',
      'MSME / Udyam Enterprise',
      'Partnership Firm',
    ],
    benefitType: 'Green Technology Grant',
    maxBenefit: '40% Accelerated Depreciation + Net Metering Tariff Concessions & Duty Exemption',
    description:
      'Assists high-power industrial enterprises in establishing captive on-site rooftop solar and battery storage systems, slashing high industrial electricity tariffs and earning green energy certificates.',
    keyBenefits: [
      '40% accelerated depreciation on solar rooftop and energy-saving machinery in Year 1',
      'Exemption from electricity duty on captive renewable self-consumption for 10 years',
      'Concessional wheeling and transmission banking charges for open-access green power',
    ],
    eligibilityConditions: [
      'Industrial premises with minimum 100 kVA sanctioned connected load from DISCOM',
      'Available unshaded roof area or ground perimeter with certified structural load capacity',
      'Installation of MNRE approved ALMM solar modules and BIS certified inverters',
    ],
    requiredDocuments: [
      {
        id: 'doc_solar_discom',
        name: 'DISCOM Net Metering / Grid Connectivity Feasibility Approval',
        description: 'Power distribution company technical feasibility order for grid parallel operation.',
        mandatory: true,
        matchingDocCode: 'DOC_DISCOM_SANCTION',
      },
      {
        id: 'doc_solar_ceig',
        name: 'Chief Electrical Inspector to Government (CEIG) Statutory Approval',
        description: 'Electrical safety and transformer synchronization permit.',
        mandatory: true,
      },
      {
        id: 'doc_solar_struct',
        name: 'Structural Engineer Stability Certificate for Factory Roof',
        description: 'Certified dead load and wind velocity resilience report for PV arrays.',
        mandatory: true,
      },
    ],
    requiredClearances: ['DISCOM_POWER_SANCTION'],
    officialPortal: 'https://solarrooftop.gov.in',
    nodalAgency: 'State Renewable Energy Development Agency (e.g. MEDA, GEDA, TEDA)',
    isDemonstration: true,
  },
  {
    id: 'demo_scheme_atufs_textiles',
    name: 'Amended Technology Upgradation Fund Scheme (ATUFS) for Textiles',
    shortName: 'ATUFS Textile Capital Subsidy',
    sponsoringBody: 'Ministry of Textiles, Government of India',
    level: 'Central',
    applicableIndustries: ['textiles'],
    applicableProjectTypes: [
      'Greenfield Manufacturing Unit',
      'Greenfield / New Unit',
      'New Unit',
      'Expansion',
      'Modernization',
    ],
    minInvestmentInrCrores: 2.0,
    maxInvestmentInrCrores: 200.0,
    applicableBusinessTypes: [
      'Private Limited Company',
      'Public Limited Company',
      'MSME / Udyam Enterprise',
      'Limited Liability Partnership (LLP)',
      'Partnership Firm',
    ],
    benefitType: 'Capital Subsidy',
    maxBenefit: '10% to 15% Capital Investment Subsidy on Benchmark Machinery (Max ₹30 Cr)',
    description:
      'Flagship national scheme promoting state-of-the-art weaving, processing, garmenting, and technical textile manufacturing with direct capital subsidies on benchmark automated machinery.',
    keyBenefits: [
      '15% capital investment subsidy for garmenting and technical textile manufacturing machinery (up to ₹30 Cr)',
      '10% capital subsidy for weaving, dyeing, and automated processing machinery (up to ₹20 Cr)',
      'Direct electronic subsidy transfer to loan account upon verification of machinery installation',
    ],
    eligibilityConditions: [
      'Procurement of designated energy-efficient benchmark machinery from certified manufacturers',
      'Credit linkage via term loan sanctioned by scheduled commercial bank or SIDBI',
      'Physical inspection and geo-tagging of installed machinery prior to subsidy release',
    ],
    requiredDocuments: [
      {
        id: 'doc_atufs_uam',
        name: 'Udyam Registration / Corporate Incorporation Certificate',
        description: 'Proof of commercial entity status and textile classification.',
        mandatory: true,
        matchingDocCode: 'DOC_UDYAM_CIN',
      },
      {
        id: 'doc_atufs_loan',
        name: 'Bank Term Loan Sanction & Disbursement Schedule',
        description: 'Sanction letter referencing ATUFS UID registration.',
        mandatory: true,
      },
      {
        id: 'doc_atufs_mach',
        name: 'Original Machinery Manufacturer Invoices & Custom Bills of Entry',
        description: 'Certified invoices proving machinery model complies with benchmark guidelines.',
        mandatory: true,
      },
      {
        id: 'doc_atufs_cte',
        name: 'State Pollution Control Board Consent to Establish (CTE)',
        description: 'Valid pollution board clearance for textile dyeing / finishing operations.',
        mandatory: true,
        matchingDocCode: 'DOC_SPCB_CTE',
      },
    ],
    requiredClearances: ['SPCB_CTE', 'FACTORY_PLAN_APPROVAL'],
    officialPortal: 'https://txcindia.gov.in',
    nodalAgency: 'Office of the Textile Commissioner, Mumbai',
    isDemonstration: true,
  },
];
